version: "3"
#networks:
#  api_server_default:
#    external: true
services:
  ecommerce_app:
    #    networks:
    #      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: production
    ports:
      - "8000:8000"