version: "3"
services:
  node:
    image: "node:19-alpine"
    user: "node"
    working_dir: /opt/project
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/opt/project
    expose:
      - "8000"
    build:
      context: .
    command: > 
      sh -c "npm install && 
             npm run start"